# Generated by Django 6.0.4 on 2026-05-06 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Overclock', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_digital',
            field=models.BooleanField(default=False),
        ),
    ]
