# Generated by Django 6.0.4 on 2026-05-06 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Overclock', '0005_category_is_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='license_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
