# Generated by Django 6.0.4 on 2026-05-06 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Overclock', '0006_order_delivery_email_order_license_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_digital',
            field=models.BooleanField(default=False),
        ),
    ]
