# Generated by Django 6.0.4 on 2026-05-07 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Overclock', '0007_orderitem_is_digital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(help_text="Shown on banners e.g. '20% off all GPUs'")),
                ('promo_type', models.CharField(choices=[('PERCENTAGE', 'Percentage Off'), ('FREE_PRODUCT', 'Free Product with Purchase')], max_length=20)),
                ('discount_percent', models.IntegerField(blank=True, null=True)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('applies_to_category', models.CharField(blank=True, help_text='Leave blank to apply to entire cart', max_length=100)),
                ('coupon_code', models.CharField(help_text='User enters this at checkout', max_length=50, unique=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('free_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='free_in_promos', to='Overclock.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
