# Generated by Django 6.0.4 on 2026-05-10 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Overclock', '0010_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='applies_to_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_promos', to='Overclock.product'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='promo_type',
            field=models.CharField(choices=[('PERCENTAGE', 'Percentage Off'), ('FREE_PRODUCT', 'Free Product with Purchase'), ('PRODUCT_DISCOUNT', 'Single Product Discount')], max_length=20),
        ),
    ]
