# Generated by Django 6.0.4 on 2026-05-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Overclock', '0011_promotion_applies_to_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='promo_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
